[hotkeys]
"Ctrl+F" = "grid"
"Ctrl+S" = "action scroll"

[hints]
enabled = false

[grid]
font_family = "JetBrainsMonoNLNFP-ExtraBold"

sublayer_keys = "gcrhtnmwv"

[action]
# Action key mappings
left_click_key = "h"
middle_click_key = "t"
right_click_key = "n"
mouse_down_key = "c"
mouse_up_key = "r"

[logging]
# Log level: "debug", "info", "warn", "error"
# Use "debug" for troubleshooting; default is "info".
log_level = "debug"
